image: Visual Studio 2015
configuration:
- Debug
- Release
platform:
- Win32
- x64
build:
  project: Project64.sln
  verbosity: minimal
artifacts:
- path: Bin
- path: build
- path: Config
- path: ipch
- path: Plugin
- path: Plugin64
