image: Visual Studio 2015
configuration:
- Debug
- Release
platform:
- Win32
- x64
build:
  project: Project64.sln
  verbosity: minimal
artifacts:
- path: bin/**
  name: first
- path: obj/**
  name: seocnd
